console.log(`=================================================== Assignment-01 ======================================`);
const arrayFruits = ["Banana", "Orange", "Apple", "Mango", "Water Melon"];
console.log(`Given Array is==>> ${arrayFruits} `);
console.log(`------------------------------------------------------------------------------`);
arrayFruits[0];
console.log(`First element In given array===>>${arrayFruits[0]}`);
console.log(`----------------------------------------------------------------------------`);
let length=arrayFruits.length;
arrayFruits[4];
console.log(`Element at last In Given array=====>> ${arrayFruits[arrayFruits.length-1]}`);
console.log(`-----------------------------------------------------------------------------`);
arrayFruits.unshift("Papaya");
console.log(`Added papaya word before banana ===>>${arrayFruits}`);
console.log(`-----------------------------------------------------------------------------`);
arrayFruits.splice(4,1);
console.log(`Removed Mango From The String ===>> ${arrayFruits}`);
console.log(`----------------------------------------------------------------------------`);
arrayFruits.push("Pineapple")
console.log(`Added Pineapple at last ===>>${arrayFruits}`);
console.log(`-----------------------------------------------------------------------------`);
arrayFruits.splice(4,0,"Dragon Fruit");
console.log(`Inserted Dragon Fruit before Water melon ==>>${arrayFruits}`);
console.log(`-----------------------------------------------------------------------------`);
arrayFruits[2]="Kiwi";
console.log(`Replaced Orange With Kiwi Fruit======>>${arrayFruits}`);
console.log(`-----------------------------------------------------------------------------`);
 let out=arrayFruits.slice(1,4);
console.log(`Slices 1 to 4  Element==>>${out}`);
console.log(`-----------------------------------------------------------------------------`);
let res=arrayFruits.slice(arrayFruits.length-3);
console.log(`Last three element===>>>${res}`);
console.log(`-----------------------------------------------------------------------------`);
console.log(`===================================================== * END * =================================================`);
